language: python
python:
    - '2.7'
before_install:
    - pip install codecov
install:
    - pip install --upgrade pytest
env:
  global:
    - PYTHONPATH=$PYTHONPATH:..:.
script:
    - py.test test
after_success:
    - coverage run --source=mdssdiff.py,test/test_mdssdiff.py -m py.test
    - codecov

