package:
    name: mdssdiff
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    noarch: python
    script: python setup.py install
    entry_points:
        - "mdssdiff = mdssdiff.mdssdiff:main_argv"

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - six

test:
    source_files:
        - setup.cfg
        - conftest.py
        - test
    requires:
        - pytest
    commands:
        - mdssdiff --help
        - py.test test/test_mdsspath.py

about:
    home: https://github.com/coecms/mdssdiff
    license: Apache 2.0
    license_file: LICENSE
    summary: Report difference between directory tree on a local filesystem and on a remote mass data store. Some rudimentary synching supported.
